/**
 * Pre-hydration theme boot script.
 *
 * Two exports:
 *   - `bootResolveTheme(...)`: a pure function the unit tests parametrise
 *     across the 4-tier precedence + the Safari private-browsing branch.
 *   - `BOOT_SCRIPT_SOURCE`: the same algorithm encoded as a self-contained
 *     IIFE string. SvelteKit's `transformPageChunk` substitutes it into
 *     `app.html` inside `%sveltekit.head%` so it runs BEFORE the runtime
 *     bundle parses, which is the only way to win the FOUC race when the
 *     server-rendered cookie path is missing or stale (e.g. localStorage
 *     was changed in another tab while the cookie still says "Storm").
 *
 * Per `m1-theming.md` § Acceptance criteria the IIFE is generated by
 * serialising the in-module function so the unit-tested module IS the
 * inlined script — `Function.prototype.toString()` does the work, the
 * function uses no closure variables, and references only globals
 * available before hydration.
 *
 * The IIFE silently catches all exceptions: a boot script that throws
 * blocks hydration in some browsers, which would be a regression from
 * "M0 ships theme-less" to "M1 ships nothing".
 */

import { THEME_IDS, type ThemeId } from '$lib/theme/presets';

/**
 * Inputs the pure function expects, modelled to mirror what the IIFE has
 * available globally. `mediaQueryDark === null` means the boot context
 * couldn't query (server, jsdom without matchMedia, browser that throws
 * on the constructor) — falls through to the brand-canonical default.
 */
export interface BootInputs {
  localStorageValue: string | null;
  cookieValue: string | null;
  mediaQueryDark: boolean | null;
}

/**
 * Four-tier precedence the IIFE encodes verbatim:
 *
 *   1. localStorage — the user's last explicit choice, if it is a
 *      currently-known preset id.
 *   2. cookie — the SSR carrier; lasts past extension cookie sweeps less
 *      reliably than localStorage but is what the server wrote.
 *   3. matchMedia('(prefers-color-scheme: dark)').matches → "tokyo-night"
 *      vs "tokyo-day" so the OS-mapped first paint is correct without an
 *      explicit choice.
 *   4. "tokyo-night" — brand-canonical fallback when no preference is
 *      available (rare; `matchMedia` returns `false` for "light" or "no
 *      preference", so the fallback only fires when matchMedia itself
 *      throws or is missing).
 */
export function bootResolveTheme(inputs: BootInputs): ThemeId {
  if (isKnownTheme(inputs.localStorageValue)) return inputs.localStorageValue;
  if (isKnownTheme(inputs.cookieValue)) return inputs.cookieValue;
  if (inputs.mediaQueryDark === true) return 'tokyo-night';
  if (inputs.mediaQueryDark === false) return 'tokyo-day';
  return 'tokyo-night';
}

function isKnownTheme(value: string | null | undefined): value is ThemeId {
  if (typeof value !== 'string') return false;
  return (THEME_IDS as readonly string[]).includes(value);
}

/**
 * The IIFE that ships into the HTML head. Authored as a function literal
 * (not a string) so it stays syntax-checked, but serialised via
 * `Function.prototype.toString()` so the runtime bundle and the inlined
 * boot share a single source. The function references only the four
 * preset ids and standard browser globals; no closure capture.
 *
 * IMPORTANT: when adding or renaming a preset id in `presets.ts`, also
 * update the inlined `ids` array below. The unit tests guard the pure
 * `bootResolveTheme` function and a separate test parses & evals
 * `BOOT_SCRIPT_SOURCE` against stubbed globals to confirm the IIFE
 * agrees with the typed module.
 */
function inlineBoot(): void {
  try {
    var ids = ['tokyo-day', 'tokyo-storm', 'tokyo-moon', 'tokyo-night'];
    var chosen = null;
    try {
      var ls = window.localStorage.getItem('theme');
      if (ls && ids.indexOf(ls) !== -1) chosen = ls;
    } catch {
      // Safari private browsing throws on localStorage access. Fall
      // through to the cookie tier — never block boot.
    }
    if (!chosen) {
      var match = document.cookie.match(/(?:^|;\s*)theme=([^;]+)/);
      if (match && match[1]) {
        try {
          var ck = decodeURIComponent(match[1]);
          if (ids.indexOf(ck) !== -1) chosen = ck;
        } catch {
          // malformed encoding; fall through.
        }
      }
    }
    if (!chosen) {
      try {
        chosen = window.matchMedia('(prefers-color-scheme: dark)').matches
          ? 'tokyo-night'
          : 'tokyo-day';
      } catch {
        chosen = 'tokyo-night';
      }
    }
    document.documentElement.dataset.theme = chosen;
  } catch {
    // Boot script must never throw. Some browsers will refuse to hydrate
    // a page whose first inline script crashes; we'd rather paint a
    // wrong theme for one frame than block hydration entirely.
  }
}

/**
 * The literal string substituted into `%theme.boot%` in `app.html` by
 * `hooks.server.ts`'s `transformPageChunk`. Wraps `inlineBoot` in
 * `()()` so it executes immediately on parse.
 *
 * Production minification preserves function bodies; the local var names
 * (`ids`, `chosen`, `ls`, `ck`, `match`) are mangle-safe because they're
 * fully scoped inside the function.
 */
export const BOOT_SCRIPT_SOURCE: string = `(${inlineBoot.toString()})()`;
