"""``chat`` table — M2 conversation surface.

Columns and indexes mirror the M2 plan ([m2-conversations.md § Data
model](../../docs/plans/m2-conversations.md)) exactly. Locked decisions
worth restating at the model level:

* ``id`` is a UUIDv7 string stored as ``VARCHAR(36)`` per
  ``rebuild.md`` §9. Generated app-side via ``app.core.ids.new_id``;
  never ``CHAR(36)``, never ``uuid.uuid4()``.
* ``created_at`` / ``updated_at`` are ``BIGINT`` epoch-milliseconds
  values generated by ``app.core.time.now_ms`` — the project-wide
  timestamp convention.
* ``history`` is a native MySQL ``JSON`` column. The shape is documented
  in [m2-conversations.md § JSON shape of chat.history] and validated
  through ``app.schemas.history.History`` on every read/write boundary
  — the column itself is raw JSON. ``dict[str, Any]`` (not bare
  ``dict``) keeps mypy strict happy.
* ``current_message_id`` is a MySQL ``GENERATED ALWAYS AS (...) STORED``
  column reflecting ``history.currentId`` so the sidebar's "current
  branch leaf" check is index-friendly without parsing JSON. SQLAlchemy
  2 has no first-class generated-column support, so the migration
  emits the ``GENERATED`` DDL out of band; the ``server_default`` here
  is **not** the live source — treat the model declaration as
  read-only on this column. See ``alembic/versions/0002_m2_chat_folder.py``.
* ``share_id`` is a placeholder ``VARCHAR(43)`` reserved for M3 (matches
  ``shared_chat.id`` width). M2 never reads or writes it; M3 owns the
  FK and the unique index ``ix_chat_share_id`` via its own Alembic
  revision (see ``rebuild/docs/plans/m3-sharing.md``).
* ``__table_args__`` declares only the five composite indexes — charset
  / collation / engine inherit from the database default set by the M0
  baseline (``database-best-practises.md`` § B.7).

ON DELETE policy:

* ``chat.user_id → user.id``: ``CASCADE`` — deleting a user destroys
  their chats. There is no anonymous-chat concept in the rebuild.
* ``chat.folder_id → folder.id``: ``SET NULL`` — deleting a folder
  detaches the chats inside (they fall back to "no folder"); deleting a
  user instead destroys the chats via the previous cascade.
"""

from __future__ import annotations

from typing import Any

from sqlalchemy import BigInteger, Boolean, ForeignKey, Index, String, Text, text
from sqlalchemy.dialects.mysql import JSON as MySQLJSON
from sqlalchemy.orm import Mapped, mapped_column

from app.core.ids import new_id
from app.core.time import now_ms
from app.db.base import Base


class Chat(Base):
    __tablename__ = "chat"

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=new_id)
    user_id: Mapped[str] = mapped_column(
        String(36),
        ForeignKey("user.id", ondelete="CASCADE"),
        nullable=False,
    )
    title: Mapped[str] = mapped_column(Text, nullable=False, default="New Chat")

    history: Mapped[dict[str, Any]] = mapped_column(
        MySQLJSON,
        nullable=False,
        server_default=text("(JSON_OBJECT('messages', JSON_OBJECT(), 'currentId', NULL))"),
    )

    folder_id: Mapped[str | None] = mapped_column(
        String(36),
        ForeignKey("folder.id", ondelete="SET NULL"),
        nullable=True,
    )

    archived: Mapped[bool] = mapped_column(Boolean, nullable=False, server_default=text("0"))
    pinned: Mapped[bool] = mapped_column(Boolean, nullable=False, server_default=text("0"))

    # Reserved for M3; declared here so M3 doesn't need an `ALTER ADD COLUMN`.
    # Always NULL in M2. Width matches `shared_chat.id` in M3. Uniqueness is
    # enforced by the M3-owned index `ix_chat_share_id` (see
    # rebuild/docs/plans/m3-sharing.md), not by a column-level UNIQUE here.
    share_id: Mapped[str | None] = mapped_column(String(43), nullable=True)

    created_at: Mapped[int] = mapped_column(BigInteger, nullable=False, default=now_ms)
    updated_at: Mapped[int] = mapped_column(BigInteger, nullable=False, default=now_ms)

    # Persistent reflection of `history.currentId`, materialised by the
    # migration as `GENERATED ALWAYS AS (...) STORED` so the sidebar's
    # "current branch leaf" check is index-friendly without parsing JSON.
    # The `server_default` below is NOT the live source — the migration
    # replaces this column with a true generated one. SQLAlchemy 2 has no
    # first-class generated-column support; do NOT mutate this column from
    # application code (writes are silently ignored by MySQL).
    current_message_id: Mapped[str | None] = mapped_column(
        String(36),
        nullable=True,
        server_default=text("(JSON_UNQUOTE(JSON_EXTRACT(history, '$.currentId')))"),
    )

    __table_args__ = (
        Index("ix_chat_user_updated", "user_id", "updated_at"),
        Index("ix_chat_user_pinned_updated", "user_id", "pinned", "updated_at"),
        Index("ix_chat_user_archived_updated", "user_id", "archived", "updated_at"),
        Index("ix_chat_user_folder_updated", "user_id", "folder_id", "updated_at"),
        Index("ix_chat_current_message", "current_message_id"),
    )
