"""``folder`` table — M2 sidebar folders for organising chats.

Columns and indexes mirror the M2 plan ([m2-conversations.md § Data
model](../../docs/plans/m2-conversations.md)) exactly. Locked decisions
worth restating at the model level:

* ``id`` is a UUIDv7 string stored as ``VARCHAR(36)`` per
  ``rebuild.md`` §9. Generated app-side via ``app.core.ids.new_id``;
  never ``CHAR(36)``, never ``uuid.uuid4()``.
* ``created_at`` / ``updated_at`` are ``BIGINT`` epoch-milliseconds
  values generated by ``app.core.time.now_ms``.
* ``__table_args__`` declares only the single ``ix_folder_user_parent``
  composite index — charset / collation / engine inherit from the
  database default set by the M0 baseline (``database-best-practises.md``
  § B.7). The folder router uses the index to satisfy the recursive CTE
  joins that compute cycle / descendant sets in one round-trip
  (m2-conversations.md § Cycle detection and descendant computation).

ON DELETE policy:

* ``folder.user_id → user.id``: ``CASCADE`` — deleting a user destroys
  their folder tree. The matching cascade on ``chat.user_id`` already
  destroys the chats themselves.
* ``folder.parent_id → folder.id``: ``CASCADE`` (self-referential) —
  deleting a folder cascades to its descendant folders. Chats inside
  the deleted folders fall back to "no folder" via the
  ``ON DELETE SET NULL`` on ``chat.folder_id``; folder cascade does NOT
  reach across to chats. This is the deliberate UX from the M2 plan:
  deleting a folder should not also delete its conversations.
"""

from __future__ import annotations

from sqlalchemy import BigInteger, Boolean, ForeignKey, Index, String, Text, text
from sqlalchemy.orm import Mapped, mapped_column

from app.core.ids import new_id
from app.core.time import now_ms
from app.db.base import Base


class Folder(Base):
    __tablename__ = "folder"

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=new_id)
    user_id: Mapped[str] = mapped_column(
        String(36),
        ForeignKey("user.id", ondelete="CASCADE"),
        nullable=False,
    )
    parent_id: Mapped[str | None] = mapped_column(
        String(36),
        ForeignKey("folder.id", ondelete="CASCADE"),
        nullable=True,
    )
    name: Mapped[str] = mapped_column(Text, nullable=False)
    expanded: Mapped[bool] = mapped_column(Boolean, nullable=False, server_default=text("0"))
    created_at: Mapped[int] = mapped_column(BigInteger, nullable=False, default=now_ms)
    updated_at: Mapped[int] = mapped_column(BigInteger, nullable=False, default=now_ms)

    __table_args__ = (Index("ix_folder_user_parent", "user_id", "parent_id"),)
