"""``shared_chat`` table — M3 anyone-with-the-link share snapshots.

Columns and indexes mirror the M3 plan ([m3-sharing.md § Data
model](../../docs/plans/m3-sharing.md)) exactly. Locked decisions
worth restating at the model level:

* ``id`` is the **share token itself**: the unpadded URL-safe base-64
  string returned by ``secrets.token_urlsafe(32)``, which is always 43
  characters wide. We store it directly as the primary key so the URL
  path segment ``/s/{token}`` is the row key — no secondary lookup, no
  separate ``token`` column. The router sets ``id`` explicitly at
  insert time; this model deliberately has **no** ``default=`` because
  share tokens are *not* UUIDv7 (`app.core.ids.new_id`) and must not
  fall back to it. Width 43 (not 64) gives MySQL a tight key and
  matches the M2-owned ``chat.share_id VARCHAR(43)`` column byte-for-
  byte so the cross-table FK lands cleanly under InnoDB's strict
  type-match rule.
* ``created_at`` is a ``BIGINT`` epoch-milliseconds value generated by
  ``app.core.time.now_ms`` — the project-wide timestamp convention
  used by every M0+ table. There is **no** ``updated_at``: a share is
  immutable after creation; re-share is delete + create (token
  rotation), as documented in ``m3-sharing.md`` § Snapshot semantics.
* ``history`` is a native MySQL ``JSON`` column carrying the same
  shape as ``chat.history`` from M2. Storing the full snapshot inline
  means ``GET /api/shared/{token}`` never has to join back to ``chat``
  — exactly what we want for a read-only view of a possibly-mutated
  original. Typed as ``dict[str, Any]`` (not bare ``dict``) for mypy
  strict; validated through ``app.schemas.history.History`` at the
  router boundary. Uses the ``mysql.JSON()`` dialect-native type (not
  generic ``sa.JSON``) so the same DDL lands here as in M2's
  ``chat.history``.
* No relationship() declared on ``SharedChat`` — and no relationship()
  on the ``Chat`` side either — to match the flat M2 style. The share
  router uses explicit joins (``shared_chat.user_id → user``) for the
  one cross-table read it does (the ``shared_by`` projection in
  ``GET /api/shared/{token}``); the API surface does not need to
  navigate the FK from the ORM, so we keep both models flat.

ON DELETE policy:

* ``shared_chat.chat_id → chat.id``: ``CASCADE`` — deleting the
  underlying chat destroys its snapshot. Without this the snapshot
  would outlive the chat it was derived from, leaving ``shared_by``
  references dangling at the user level even though the chat is gone.
* ``shared_chat.user_id → user.id``: ``CASCADE`` — deleting a user
  destroys their share rows alongside their chats (``chat.user_id``
  also cascades from M2). There is no anonymous-share concept.
* ``chat.share_id → shared_chat.id``: ``SET NULL`` — deleting a
  ``shared_chat`` row never leaves a dangling pointer on the original
  ``chat``; the back-pointer simply clears. **This FK is not declared
  on this model and is not declared on the Chat model either.** It is
  added at the DB layer by the M3 Alembic revision
  (``0003_m3_sharing``) against the M2-reserved ``chat.share_id``
  column, alongside the unique index ``ix_chat_share_id``. The ORM
  never navigates that pointer; the router reads ``chat.share_id``
  directly when it needs to know whether a chat is currently shared.

The two secondary indexes (``ix_shared_chat_chat_id`` /
``ix_shared_chat_user_id``) cover the FK columns so InnoDB doesn't
need to back the FKs with auto-generated unnamed indexes, and they
support the "find shares belonging to chat X" / "find shares created
by user Y" lookups the share router and any future revoke-by-user
audit path performs. Both indexes are non-unique: one chat may have
many *historical* share rows in the abstract sense, even though the
"at most one *active* share per chat" invariant is enforced separately
by the unique index on ``chat.share_id`` (M3 revision, not on this
model).

Charset / collation / engine inherit from the database default set by
the M0 baseline (``database-best-practises.md`` § B.7); ``__table_args__``
declares only the two indexes.
"""

from __future__ import annotations

from typing import Any

from sqlalchemy import BigInteger, ForeignKey, Index, String
from sqlalchemy.dialects.mysql import JSON as MySQLJSON
from sqlalchemy.orm import Mapped, mapped_column

from app.core.time import now_ms
from app.db.base import Base


class SharedChat(Base):
    __tablename__ = "shared_chat"

    id: Mapped[str] = mapped_column(String(43), primary_key=True)
    chat_id: Mapped[str] = mapped_column(
        String(36),
        ForeignKey("chat.id", ondelete="CASCADE"),
        nullable=False,
    )
    user_id: Mapped[str] = mapped_column(
        String(36),
        ForeignKey("user.id", ondelete="CASCADE"),
        nullable=False,
    )
    title: Mapped[str] = mapped_column(String(255), nullable=False)
    history: Mapped[dict[str, Any]] = mapped_column(MySQLJSON, nullable=False)
    created_at: Mapped[int] = mapped_column(BigInteger, nullable=False, default=now_ms)

    __table_args__ = (
        Index("ix_shared_chat_chat_id", "chat_id"),
        Index("ix_shared_chat_user_id", "user_id"),
    )
