"""``user`` table — the only ORM model created in M0.

Columns match the M0 baseline DDL exactly (see
``rebuild/plans/m0-foundations.md`` § Alembic baseline). Locked decisions
worth restating at the model level:

* ``id`` is a UUIDv7 string stored as ``VARCHAR(36)`` per
  ``rebuild.md`` §9. Generated app-side via ``app.core.ids.new_id``;
  never ``CHAR(36)``, never ``uuid.uuid4()``.
* ``created_at`` is a ``BIGINT`` epoch-milliseconds value generated by
  ``app.core.time.now_ms`` — the project-wide timestamp convention used by
  every later table (chats, channels, automations, files).
* ``email`` carries the unique constraint ``uq_user_email`` (matching the
  baseline DDL exactly); the trusted-header upsert in
  ``app.core.auth.upsert_user_from_headers`` relies on this constraint
  for its ``ON DUPLICATE KEY UPDATE`` race-free first-login path.
"""

from __future__ import annotations

from sqlalchemy import BigInteger, String, UniqueConstraint
from sqlalchemy.orm import Mapped, mapped_column

from app.core.ids import new_id  # resolved by fastapi-engineer dispatch
from app.core.time import now_ms  # resolved by fastapi-engineer dispatch
from app.db.base import Base


class User(Base):
    __tablename__ = "user"

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=new_id)
    email: Mapped[str] = mapped_column(String(320), nullable=False)
    name: Mapped[str] = mapped_column(String(255), nullable=False)
    timezone: Mapped[str] = mapped_column(String(64), nullable=False, server_default="UTC")
    created_at: Mapped[int] = mapped_column(BigInteger, nullable=False, default=now_ms)

    __table_args__ = (
        UniqueConstraint("email", name="uq_user_email"),
        {
            "mysql_engine": "InnoDB",
            "mysql_charset": "utf8mb4",
            "mysql_collate": "utf8mb4_0900_ai_ci",
        },
    )
