<!--
  Harness for the M3 public share-view CT spec.

  Path picked: option (b) — mirror the route's markup directly.
  ------------------------------------------------------------
  Per the dispatch's harness selection note (option a vs option b),
  the SvelteKit route page lives at
  `frontend/src/routes/(public)/s/[token]/+page.svelte`. Importing
  it from a CT harness is technically possible (the CT bundler
  preprocesses TS, so the `import type { PageData } from './$types'`
  line is erased at build time), but `./$types` is generated by
  `svelte-kit sync` and dragging Kit's virtual route graph into the
  CT bundler is the kind of cross-tooling coupling that breaks on
  the first refactor. Mirroring the route's markup verbatim keeps
  the harness self-contained: the spec exercises the same
  `MessageList` + `formatRelativeTime` + class structure the route
  renders, but without depending on Kit being able to satisfy the
  route file's type imports.

  If a future refactor extracts the route's markup into a real
  presentational component (`SharedSnapshotView.svelte` under
  `$lib/components/share/`), this harness should switch to mounting
  that component directly — option (a) becomes correct the moment
  the surface stops being route-only.

  Behaviour the harness exposes
  -----------------------------
  - `snapshot: SharedChatSnapshot | null` prop: `null` renders the
    dead-link panel; otherwise renders the title + subline + the
    M2 `MessageList` in `readonly` mode.
  - `now: number` prop: optional fixed clock injected into
    `formatRelativeTime` so the relative-time subline doesn't
    drift between test runs. Defaults to `snapshot.created_at + 60s`
    so the subline is deterministically `"a minute ago"`-shaped.
  - No `ActiveChatStore` context is provisioned: `MessageList` in
    `readonly` mode walks the readonly path that does NOT call
    `getContext` for it (M3 contract — the public share view never
    pulls in the (app) layout's stores).
  - A `ThemeStore` IS provisioned because the recursive Markdown
    subtree (`CodeBlock` -> Shiki, `ColonFenceBlock` -> Mermaid)
    reads it for the preset-aware syntax-highlighting cascade.
    Mirrors `MarkdownHarness.svelte`'s setup.

  Fixture data lives in `share-fixtures.ts` (sibling) so the spec
  can re-use the same constants and factories. Existing CT
  harnesses in this repo expose only their default component
  export — keeping that invariant here.
-->
<script lang="ts">
  import { setContext, untrack } from 'svelte';
  import MessageList from '$lib/components/chat/MessageList.svelte';
  import { ThemeStore, THEME_CONTEXT_KEY } from '$lib/stores/theme.svelte';
  import { formatRelativeTime } from '$lib/utils/relative-time';
  import type { SharedChatSnapshot } from '$lib/types/share';
  import { FIXTURE_NOW, defaultSnapshotFixture } from './share-fixtures';

  interface Props {
    /** Pass `null` to render the dead-link panel; otherwise the snapshot. */
    snapshot?: SharedChatSnapshot | null;
    /** Fixed clock injected into `formatRelativeTime` so the subline
     *  doesn't drift across runs. */
    now?: number;
  }

  let { snapshot = defaultSnapshotFixture(), now = FIXTURE_NOW + 60_000 }: Props = $props();

  const snapshotSnapshot = untrack(() => snapshot);
  const nowSnapshot = untrack(() => now);

  // Markdown's recursive subtree (`CodeBlock` -> Shiki, `ColonFenceBlock`
  // -> Mermaid) reads a `ThemeStore` from context for the preset-aware
  // syntax-highlighting cascade. Mirrors `MarkdownHarness.svelte`'s
  // setup so any code-fence in a share-snapshot fixture round-trips
  // through the production highlighter.
  if (typeof document !== 'undefined') {
    document.documentElement.dataset.theme = 'tokyo-night';
  }
  const themeStore = new ThemeStore({
    initial: 'tokyo-night',
    osDark: true,
    initialSource: 'explicit',
  });
  setContext(THEME_CONTEXT_KEY, themeStore);

  const sharedSubline =
    snapshotSnapshot === null
      ? null
      : `Shared by ${snapshotSnapshot.shared_by.name}, ${formatRelativeTime(snapshotSnapshot.created_at, nowSnapshot)}`;
</script>

<div class="bg-background-app text-ink-body min-h-svh">
  {#if snapshotSnapshot === null}
    <main class="mx-auto flex min-h-svh max-w-md flex-col items-center justify-center px-6 py-16">
      <div class="border-hairline bg-background-app/95 w-full rounded-3xl border p-8 text-center">
        <h1 class="text-ink-strong text-base font-medium">Shared chat unavailable</h1>
        <p class="text-ink-muted mt-2 text-sm leading-relaxed">
          This share link is no longer active.
        </p>
      </div>
    </main>
  {:else}
    <article class="mx-auto w-full max-w-3xl px-4 py-10 md:py-14">
      <header class="border-hairline mb-6 border-b pb-6">
        <h1 class="text-ink-strong font-display text-xl leading-tight font-semibold">
          {snapshotSnapshot.title}
        </h1>
        {#if sharedSubline}
          <p class="text-ink-muted mt-1.5 text-xs">
            {sharedSubline}
          </p>
        {/if}
      </header>

      <MessageList history={snapshotSnapshot.history} readonly />
    </article>
  {/if}
</div>
